name: Ktlint

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ktLint
        run: ./gradlew ktlintCheck